language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update || true
    - composer install --dev --prefer-source
    - mkdir -p web/code-coverage

script:
    - vendor/bin/atoum

notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change
